# Generated by Django 4.2.4 on 2023-11-15 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kor_co_nm', models.CharField(max_length=15)),
                ('fin_prdt_nm', models.CharField(max_length=30)),
                ('intr_rate_type', models.CharField(max_length=4)),
                ('save_trm', models.IntegerField()),
                ('intr_rate', models.FloatField()),
            ],
        ),
    ]
