# Generated by Django 4.2.4 on 2023-11-15 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kor_co_nm', models.CharField(max_length=15)),
                ('fin_prdt_nm', models.CharField(max_length=30)),
                ('crdt_grad_avg', models.FloatField()),
            ],
        ),
    ]
